# Site wide configuration

title:            Caged Crown
locale:           en_US
url:              


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Maury Lindo
  avatar: bio-photo.jpg
  bio: "Cool Guy."
  email: mo@cagedcrown.com
  disqus-shortname: cagedcrown
  twitter: cagedrown
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: cagedcrown
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: cagedcrown
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: cagedcrown
  youtube: #username
  soundcloud: #username
  codepen: cagedcrown

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
