# Site wide configuration

title: Caged Crown
description: "A blog about code, design, and habits"
logo: 120x120.gif
teaser: teaser_400x250.png
locale: en_US
url: //cagedcrown.com

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Maury Lindo
  web: http://cagedcrown.com
  email: mo@cagedcrown.com
  twitter: cagedcrown
  bio: "Designer turned developer."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: #+MichaelRoseDesign
    ad-client: #ca-pub-7328585512091257
    ad-slot: #3049671934
  disqus-shortname: cagedcrown


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]